name: My Workflow hehe

on:
  pull_request: {}

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out and run my script yay
        run: |
          echo "$GITHUB_HEAD_REF"
          echo "$GITHUB_BASE_REF"
          echo "$GITHUB_SHA"
          git checkout "$GITHUB_HEAD_REF"
          git checkout "$GITHUB_BASE_REF"
          git checkout "$GITHUB_SHA"
          echo "Hello this is a test hehe"
          ./scripts/my-script-hehe.sh

